name: Natural Daily Contributions

on:
  schedule:
    # Runs once a day at 12:00 UTC (5:30 PM IST)
    - cron: "0 12 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  commit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configure Git author
        run: |
          git config user.name "${{ github.actor }}"
          git config user.email "${{ secrets.USER_EMAIL }}"

      - name: Random number of commits
        run: |
          COMMITS=$(( ( RANDOM % 6 )  + 1 ))
          echo "Making $COMMITS commits today"
          for i in $(seq 1 $COMMITS); do
            echo "$(date -u) - Commit $i" >> .keepalive
            git add .keepalive
            git commit -m "chore: daily contribution $i at $(date -u +'%Y-%m-%dT%H:%M:%SZ')"
          done

      - name: Push changes
        run: git push
